"""empty message

Revision ID: 379bb30aa813
Revises: a33b87bf42cc
Create Date: 2025-11-04 13:31:04.914007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '379bb30aa813'
down_revision = 'a33b87bf42cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moon',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('planet_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['planet_id'], ['planet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('moon')
    # ### end Alembic commands ###
