"""empty message

Revision ID: 734841dd5d17
Revises: 379bb30aa813
Create Date: 2025-11-04 14:17:28.874121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '734841dd5d17'
down_revision = '379bb30aa813'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('moon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('size', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('has_life', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('moon', schema=None) as batch_op:
        batch_op.drop_column('has_life')
        batch_op.drop_column('description')
        batch_op.drop_column('size')

    # ### end Alembic commands ###
